# Generated by Django 6.1.1 on 2026-09-26 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mutint_experiment', '__first__'),
        ('mutint_sample', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastqcReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255)),
                ('fastqc_version', models.CharField(blank=True, max_length=32)),
                ('encoding', models.CharField(blank=True, max_length=64)),
                ('total_sequences', models.BigIntegerField(blank=True, null=True)),
                ('poor_quality', models.BigIntegerField(blank=True, null=True)),
                ('length_min', models.IntegerField(blank=True, null=True)),
                ('length_max', models.IntegerField(blank=True, null=True)),
                ('gc_percent', models.FloatField(blank=True, null=True)),
                ('total_bases', models.CharField(blank=True, max_length=32)),
                ('modules', models.JSONField(default=dict)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fastqc_reports', to='mutint_experiment.experiment')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fastqc_reports', to='mutint_sample.sample')),
            ],
            options={
                'ordering': ['file_name', 'pk'],
            },
        ),
    ]
